name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Compress dist files
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r dist.zip dist

    - name: List files after zipping
      run: ls -la

    - name: Copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.RASPI_HOST }}
        username: ${{ secrets.RASPI_USERNAME }}
        password: ${{ secrets.RASPI_PASSWORD }}
        port: 22
        source: "dist.zip"
        target: "Documents/code/product-db-web-refine"
      
