name: Build and deploy

on:
  push:
    branches: [ main ]

env:
  VITE_API_URL: ${{ secrets.API_URL }}
  PM2_PATH: ${{ secrets.PM2_PATH }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: List files after build
      run: ls -la dist

    - name: Copy dist files to target host via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.RASPI_HOST }}
        username: ${{ secrets.RASPI_USERNAME }}
        password: ${{ secrets.RASPI_PASSWORD }}
        port: 22
        source: "dist/**"
        target: "Documents/code/product-db-web-refine"
        rm: true
        timeout: 60s

    - name: Reload application on target host
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.RASPI_HOST }}
        username: ${{ secrets.RASPI_USERNAME }}
        password: ${{ secrets.RASPI_PASSWORD }}
        port: 22
        timeout: 60s
        script: |
          ${{ env.PM2_PATH }} status
          ${{ env.PM2_PATH }} reload product-db-web
          
